# Generated by Django 5.1.2 on 2024-11-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('student', 'Student'), ('contact', 'Contact')], max_length=20),
        ),
    ]
